# Generated by Django 4.2 on 2023-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_post_categories_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
