# Generated by Django 4.2 on 2023-09-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_category_sub_title_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advertisment',
            field=models.CharField(blank=True, default='None', max_length=25, null=True),
        ),
    ]
