# Generated by Django 4.2 on 2023-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category_advertisment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='advertisment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
