# Generated by Django 4.2 on 2023-09-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_category_advertisment'
         ),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='advertisment',
            new_name='advertisement',
        ),
    ]
