# Generated by Django 4.2 on 2023-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_advertisment_category_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_order',
            field=models.IntegerField(default=99),
        ),
    ]
