# Generated by Django 4.2 on 2023-09-10 21:51

from django.db import migrations


def add_example_Category(apps, schema_editor):
    # Get the model for which you want to add a row
    Category = apps.get_model('website', 'Category')
    
    # Create a new row
    category = Category(title = "Other",
                        sub_title = "Default Category",
                        slug = "other",
                        thumbnail = None,
                        advertisement = "Miscellaneous"
                        )
    category.save()




class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_category_thumbnail_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RunPython(add_example_Category),
    ]
