# Generated by Django 4.2.13 on 2024-10-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_skillprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mobile_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
