# Generated by Django 4.2.13 on 2024-10-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_project_mobile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hosted_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
