# Generated by Django 4.2.13 on 2024-10-18 13:19

from django.db import migrations, models
import website.storage


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_project_github_url_alter_project_hosted_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mobile_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=website.storage.MyStorage(options={'api_key_name': 'BUNNY_CDN_API_KEY', 'remote_storage_folder': 'personal-site', 'storage_zone': 'minimum-europe', 'storage_zone_region': 'de'}), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(storage=website.storage.MyStorage(options={'api_key_name': 'BUNNY_CDN_API_KEY', 'remote_storage_folder': 'personal-site', 'storage_zone': 'minimum-europe', 'storage_zone_region': 'de'}), upload_to=''),
        ),
    ]
